spring:
  application:
    name: gateway-server
  cloud:
    gateway:
        routes:
            - id: user
              uri: http://localhost:8090
              predicates:
                - Path=/users/**
            - id: post
              uri: http://localhost:8091
              predicates:
                - Path=/posts/**
              filters:
                - JwtValidationFilterFactory
            - id: user2
              uri: http://localhost:8090
              predicates:
                - Path=/users/myinfo
              filters:
                - JwtValidationFilterFactory
  config:
    import: optional:configserver:http://localhost:8888
server:
    port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka