spring:
    application:
      name: gateway-server
    cloud:
      gateway:
          routes:
              - id: user
                uri: http://localhost:8081
                predicates:
                    - Path=/user/**
              - id: post
                uri: http://localhost:8082
                predicates:
                    - Path=/post/**

server:
    port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka