spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/board_db?serverTimezone=Asia/Seoul&characterEncoding=utf8
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: none #create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace

jwt:
  secret: "stir"
  expiration: 86400000